### ISSUE TITLE
Disabled antialiased rendering in the joker preview

### ISSUE THREAD

**Issue by marralesfios** [cozyGalvinism/BalaUI#1]
Add this to the CSS:
```css
.h-full {
    image-rendering: crisp-edges;
}
```
